[workspace.package]
version = "2.0.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/RedstoneWizard08/Wormhole"
homepage = "https://github.com/RedstoneWizard08/Wormhole"
authors = ["RedstoneWizard08", "Rexicon226", "cheese3660", "Wormhole Contributors"]

[workspace.dependencies]
wormhole-common = { path = "./common" }
tokio = { version = "1.36.0", features = ["full"] }
serde_json = "1.0.114"
serde = { version = "1.0.197", features = ["derive"] }
tauri = { version = "1.6.1", features = ["api-all"] }
zip-extensions = "0.6.2"
keyvalues-parser = "0.2.0"
ckandex = "0.6.3"
reqwest = { version = "0.11.26", features = ["stream", "gzip"] }
tokio-util = { version = "0.7.10", features = ["full"] }
tokio-stream = { version = "0.1.15", features = ["tokio-util", "fs", "net", "sync"] }
tauri-build = "1.5.1"
clap = { version = "4.1.8", features = ["derive", "env", "string"] }
rusqlite = { version = "0.31.0", features = ["bundled"] }
rand = "0.8.5"
zip = "0.6.6"
async-trait = "0.1.78"
lazy_static = "1.4.0"
chrono = { version = "0.4.35", features = ["serde"] }

[workspace]
resolver = "2"

members = [
    "cli",
    "common",
    "gui"
]
