[package]
name = "macro-test"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true

[dependencies]
macros.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
