name: Clippy

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup # Pull this step from `oscartbeaumont/specta`
        run: sudo apt-get install librust-atk-dev libwebkit2gtk-4.0-dev build-essential libssl-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev
      
      - name: Install Rust toolchain
        run: rustup toolchain install stable --profile minimal --component clippy
      
      - name: Rust cache
        uses: Swatinem/rust-cache@v2
      
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features