[package]
name = "wormhole-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.1.8", features = ["derive", "env", "string", "debug"] }
tokio = { version = "1.26.0", features = ["full"] }
wormhole-common = { path = "../common" }
