[package]
name = "example"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
rspc = { path = "../", features = ["axum"] }
async-stream = "0.3.4"
axum = "0.6.7"
chrono = { version = "0.4.23", features = ["serde"] }
serde = { version = "1.0.152", features = ["derive"] }
time = "0.3.19"
tokio = { version = "1.25.0", features = ["rt-multi-thread", "macros", "time", "sync"], default-features = false }
tower-http = { version = "0.3.5", default-features = false, features = ["cors"] }
uuid = { version = "1.3.0", features = ["v4", "serde"] }
serde_json = "1.0.93"
