[package]
name = "plugin-tester"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true

[dependencies]
api.workspace = true
anyhow.workspace = true
