[package]
name = "instance"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true

[dependencies]
chrono.workspace = true
anyhow.workspace = true
query.workspace = true
