name: Publish (Linux)
on: [push]

jobs:
    publish-tauri-amd64:
        permissions:
            contents: write
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: recursive

            - name: setup node
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: install Rust nightly
              uses: dtolnay/rust-toolchain@nightly
            
            - name: Fix Rust
              run: rustup update

            - name: Install system dependencies
              run: |
                  sudo apt-get update
                  sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

            - name: Install pnpm
              run: npm i -g pnpm

            - name: Install frontend dependencies
              run: pnpm install

            - uses: benjlevesque/short-sha@v2.1
              id: short-sha
              with:
                  length: 7

            - name: Run conf
              run: ./apps/gui/genconf.sh

            - name: Build app
              run: |
                  touch .env
                  pnpm run build
                  cargo build --release
              env:
                CURSEFORGE_KEY: ${{ secrets.CURSEFORGE_KEY }}
                MSA_CLIENT_SECRET: ${{ secrets.MSA_CLIENT_SECRET }}
                NEXUS_API_KEY: ${{ secrets.NEXUS_API_KEY }}

            - uses: actions/upload-artifact@v4
              with:
                  name: Linux Binaries (x86_64)
                  path: |
                      target/release/wormhole
                      target/release/wormhole_gui
                      target/release/wormhole_cli
                      target/release/bindings
                      target/release/webui
                      target/release/*.exe

                      target/release/*.tar.gz
                      target/release/*.tar.gz.sig
                      target/release/*.dmg
                      target/release/*.AppImage
                      target/release/*.AppImage.tar.gz
                      target/release/*.AppImage.tar.gz.sig
                      target/release/*.deb
                      target/release/*.rpm
                      target/release/*.msi
                      target/release/*.msi.zip
                      target/release/*.msi.zip.sig
                      target/release/*.nsis.zip
                      target/release/*.nsis.zip.sig
